--2023-02-09 17:45:50--  http://localhost:8080/run_task?command=python
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:45:51--  (try: 2)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:45:53--  (try: 3)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:45:56--  (try: 4)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:00--  (try: 5)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:05--  (try: 6)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:11--  (try: 7)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:18--  (try: 8)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:26--  (try: 9)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:35--  (try:10)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:45--  (try:11)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:46:55--  (try:12)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:05--  (try:13)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:15--  (try:14)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:25--  (try:15)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:35--  (try:16)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:45--  (try:17)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:47:55--  (try:18)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:48:05--  (try:19)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2023-02-09 17:48:15--  (try:20)  http://localhost:8080/run_task?command=python
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... No data received.
Giving up.

--2023-02-09 17:48:15--  http://test.py/
Resolving test.py (test.py)... failed: Name or service not known.
wget: unable to resolve host address ‘test.py’
